# -*- coding: utf-8 -*-
"""Classify_C1_MentalQA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r3aK6Xp102MvhChSS-LTnvPqA7b0MiqO?usp=sharing

# The First Classifier #1: `Classify a question into one or more categories.`

# Packages

## pack-1
"""


"""## pack-2"""


"""## pack-3"""


import torch
import ast
import random
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from tqdm import tqdm
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    Trainer,
    TrainingArguments
)
from datasets import Dataset, Sequence, Value
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score, accuracy_score, precision_recall_fscore_support, classification_report

"""# Dataset"""

df = pd.read_csv('MentalQA_500_data.csv', sep="\t")
df

# Getting all the unique labels
df["final_QT"].unique()

# Getting the data that has the Z label
df[df['final_QT'].str.contains('Z')]

# For Data augs
#1
def random_deletion(words, p=0.1):
    """
    Randomly deletes each word with probability p.
    words: list of tokens.
    """
    # If only one word, just return it
    if len(words) == 1:
        return words

    new_words = []
    for w in words:
        # With probability p, drop the word
        if random.uniform(0,1) > p:
            new_words.append(w)
    # If everything deleted, return 1 word
    if len(new_words) == 0:
        return [random.choice(words)]
    return new_words
#2
def random_swap(words, n=1):
    """
    Randomly swap the positions of two words n times.
    words: list of tokens
    """
    new_words = words.copy()
    for _ in range(n):
        idx1, idx2 = random.sample(range(len(new_words)), 2)
        new_words[idx1], new_words[idx2] = new_words[idx2], new_words[idx1]
    return new_words
#3
def augment_text_arabic(text, alpha_delete=0.1, swaps=1):
    """
    Apply random_deletion + random_swap to text and return multiple augmented variants.
    """
    words = text.split()

    # 1) Random Deletion
    words_del = random_deletion(words, p=alpha_delete)
    text_del = " ".join(words_del)

    # 2) Random Swap
    words_swap = random_swap(words, n=swaps)
    text_swap = " ".join(words_swap)

    return [text_del, text_swap]

# 1. Convert the string representation into a Python list
df["final_QT"] = df["final_QT"].apply(ast.literal_eval)

# 2. Collect all unique categories
all_cats = ["A", "B", "C", "D", "E", "F", "G"] # Z shouldn't be here it is G
# 3. In each list, replace 'Z' with 'G'
def fix_z(labels):
    return ['G' if x == 'Z' else x for x in labels]

df["final_QT"] = df["final_QT"].apply(fix_z)
#4. Augs
df_aug_rows = []
for idx, row in df.iterrows():
    # create 2 augmented examples
    for aug_text in augment_text_arabic(row["question"]):
        df_aug_rows.append({"question": aug_text, "final_QT": row["final_QT"]})
df_aug = pd.DataFrame(df_aug_rows)

#5. Combine
df_full = pd.concat([df, df_aug], ignore_index=True)

# 6. Convert each rowâ€™s list of categories into a multi-hot vector
label_list = sorted(all_cats)  # or define a stable order: ["A","B","C","D","E","F","G"]
cat2id = {cat: i for i, cat in enumerate(label_list)}
def encode_labels(lst):
    v = np.zeros(len(label_list), dtype=np.float32)
    for lab in lst:
        v[cat2id[lab]] = 1.0
    return v

df_full["q_label_vec"] = df_full["final_QT"].apply(encode_labels)

# getting a distribution of the labels to see if they are balance
df["final_QT"].value_counts()

# plotting it
df["final_QT"].value_counts().plot(kind="barh")

df_full

df_full.drop(columns=["final_QT", "answer","final_AS"], inplace=True)

df_full

# Spliting the features
X= df_full['question']
y= df_full['q_label_vec']

# sample
print(X.loc[1])
print(y[1])

# Spliting the data into:
# Train 70% | Test 15% | Dev 15%
X_train , X_test_valid , y_train , y_test_valid = train_test_split(X,y ,test_size=0.3, random_state=42)
X_test , X_valid , y_test , y_valid = train_test_split(X_test_valid, y_test_valid, test_size=0.5, random_state=42)

# displaying the shapes
print(f"X_train shape", X_train.shape)
print(f"X_test shape", X_test.shape)
print(f"y_train shape", y_train.shape)
print(f"y_test shape", y_test.shape)

# Converting it from df into huggingface (dataset)
train_df = pd.DataFrame({
    "question": X_train,
    'q_label_vec': y_train,
})
test_df = pd.DataFrame({
    "question": X_test,
    'q_label_vec': y_test,
})
valid_df = pd.DataFrame({
    "question": X_valid,
    'q_label_vec': y_valid,
})

train_dataset = Dataset.from_pandas(train_df)
test_dataset = Dataset.from_pandas(test_df)
valid_dataset = Dataset.from_pandas(valid_df)

print("Train size:", len(train_dataset))
print("Test size:", len(test_dataset))
print("Valid size:", len(valid_dataset))

train_dataset["question"][0]

train_dataset["q_label_vec"][0]

"""# AraBERTv02 fine-tuning

## 1- Load the AraBERT Tokenizer
"""

model_name = "aubmindlab/bert-base-arabertv02"
tokenizer = AutoTokenizer.from_pretrained(model_name)

"""## 2- Tokenize the Datasets"""

def tokenize_function(examples):
    return tokenizer(
        examples["question"],
        truncation=True,
        padding='max_length',  # or "longest" (but for training, 'max_length' is common)
        max_length=128
    )

# apply the tokenizer
train_dataset = train_dataset.map(tokenize_function, batched=True)
test_dataset  = test_dataset.map(tokenize_function, batched=True)
valid_dataset = valid_dataset.map(tokenize_function, batched=True)

"""## 3-  Set Format and Remove Unused Columns"""

# columns_to_remove = ["question", "__index_level_0__"]  # adapt to whatever columns appear

# train_dataset = train_dataset.remove_columns([col for col in columns_to_remove if col in train_dataset.column_names])
# test_dataset  = test_dataset.remove_columns([col for col in columns_to_remove if col in test_dataset.column_names])
# valid_dataset = valid_dataset.remove_columns([col for col in columns_to_remove if col in valid_dataset.column_names])

train_dataset = train_dataset.rename_column("q_label_vec", "labels")
test_dataset = test_dataset.rename_column("q_label_vec", "labels")
valid_dataset = valid_dataset.rename_column("q_label_vec", "labels")

train_dataset = train_dataset.cast_column("labels", Sequence(feature=Value("float")))
test_dataset = test_dataset.cast_column("labels", Sequence(feature=Value("float")))
valid_dataset = valid_dataset.cast_column("labels", Sequence(feature=Value("float")))

train_dataset.set_format("torch")
test_dataset.set_format("torch")
valid_dataset.set_format("torch")

train_dataset

"""## 4- Load the Model for Multi-Label Classification"""

num_labels = len(y_train.iloc[0]) # 7 = from A to G
model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    num_labels=num_labels,
    problem_type="multi_label_classification"
)

"""## 5- Define Training Arguments"""

training_args = TrainingArguments(
    output_dir="c1-questions-model",  # or any temporary folder
    evaluation_strategy="epoch",
    save_strategy="no",              # no intermediate saves
    num_train_epochs=30,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    learning_rate=1e-5,
    load_best_model_at_end=False,    # can't load best model if not saving
    metric_for_best_model="f1",
    greater_is_better=True,
    logging_steps=50,
    report_to="none"
)

"""## 6- Create a `compute_metrics` Function"""

def multi_label_metrics(eval_pred):
    logits, labels = eval_pred
    # Apply sigmoid
    probs = 1 / (1 + np.exp(-logits))
    # Binarize predictions
    y_pred = (probs > 0.5).astype(int)

    # Flatten or not? Because it's multi-label, we do it label-wise
    precision, recall, f1, _ = precision_recall_fscore_support(labels, y_pred, average='micro')
    acc = accuracy_score(labels, y_pred)  # Not super informative for multi-label, but we can compute it

    return {
        "precision": precision,
        "recall": recall,
        "f1": f1,
        "accuracy": acc
    }

"""## 7- Create the Trainer and Train"""

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=valid_dataset,   # for validation
    tokenizer=tokenizer,          # helps with text decoding if needed
    compute_metrics=multi_label_metrics
)

trainer.train()

"""# Evaluation"""

test_metrics = trainer.evaluate(test_dataset)
print("Test metrics:", test_metrics)

valid_metrics = trainer.evaluate(valid_dataset)
print("Valid metrics:", valid_metrics)

def sigmoid(logits):
    return 1 / (1 + np.exp(-logits))

# ----------------------
# Validation Set
# ----------------------
valid_output = trainer.predict(valid_dataset)
valid_logits = valid_output.predictions # numbers = [3.16, -2, 1.9, ...]
valid_labels = valid_output.label_ids  # ground-truth multi-hot labels from dataset "y_valid TBH"
valid_probs = sigmoid(valid_logits) # sigmoid(numbers)
# Pred
valid_preds = (valid_probs > 0.5).astype(int)
# classification_report for multi-label


print("Validation Classification Report")
print(
    classification_report(
        valid_labels,
        valid_preds,
        target_names=all_cats,   # so each label's name is displayed
        zero_division=0         # avoid divide-by-zero warnings if a label is missing
    )
)

# ----------------------
# Test Set
# ----------------------
test_output = trainer.predict(test_dataset)
test_logits = test_output.predictions
test_labels = test_output.label_ids
test_probs = sigmoid(test_logits)
# Pred
test_preds = (test_probs > 0.5).astype(int)

print("Test Classification Report")
print(
    classification_report(
        test_labels,
        test_preds,
        target_names=all_cats,
        zero_division=0
    )
)

test_dataset["labels"][:5]

test_preds[:5]


"""# Save & Load model"""

# trainer.save_model("my_c1_model_97_f1_test_valid")

# Save it in the drive

# !cp -r /content/my_c1_model_97_f1_test_valid /content/drive/MyDrive/my_c1_model_97_f1_test_valid

model_path = "./my_c1_model_97_f1_test_valid"
model_past = AutoModelForSequenceClassification.from_pretrained(model_path)
tokenizer_past = AutoTokenizer.from_pretrained(model_path)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model_past.eval()

"""# Just Making Prediction"""

def predict_labels(texts, threshold=0.9):
    # If user passes a single string, make it a list for uniform processing
    if isinstance(texts, str):
        texts = [texts]

    # Tokenize (batch)
    inputs = tokenizer_past(
        texts,
        return_tensors="pt",
        padding=True,
        truncation=True,
        max_length=128
    )

    with torch.no_grad():
        outputs = model_past(**inputs)
        # shape [batch_size, num_labels]
        logits = outputs.logits

    # Convert logits -> probabilities
    probs = torch.sigmoid(logits).cpu().numpy()

    # Threshold
    predictions = (probs > threshold).astype(int)

    # Decode label indices to label names
    all_results = []
    for pred_row in predictions:
        label_indices = np.where(pred_row == 1)[0]
        predicted_labels = [all_cats[idx] for idx in label_indices]
        all_results.append(predicted_labels)

    return all_results

y_test = test_dataset["q_label_vec"]

# Making the prediction from the saved model using tqdm ##### Ask GPT about the random shift ?
y_pred_test = []
for text in tqdm(test_dataset["question"]):
    y_pred_test.append(predict_labels(text)[0])

# Convert the 'y_pred_test' into one hot encoding
def categories_to_multihot(cat_list, cat2id):
    """
    Convert a list of labels (e.g. ["A","C"]) into a multi-hot vector
    using the mapping cat2id.
    """
    num_labels = len(cat2id)
    vec = np.zeros(num_labels, dtype=int)
    for cat in cat_list:
        if cat in cat2id:  # double-check label is valid
            vec[cat2id[cat]] = 1
    return vec

y_pred_test = [categories_to_multihot(cat_list, cat2id) for cat_list in y_pred_test]

y_test[:5]

y_pred_test[:5]

### classifcation report on test data ###
print("Threshold: ", 0.4)
print("Test Classification Report")
print(
    classification_report(
        y_test,
        y_pred_test,
        target_names=all_cats,
        zero_division=0
    )
)

"""# Use FineTuned model on SHEFAA dataset"""

# Single example
# Single text
# text = " اعاني من الغثيان بسبب الادوية"
text = "أعاني من القلق الشديد والخوف من المستقبل"
predicted = predict_labels(text)
print("Text:", text)
print("Predicted labels:", predicted[0])

# 1) Load your original dataset
df_original = pd.read_csv("MentalHealthQA.csv")  # adjust path, columns as needed
# Data filtering using my model
df_original

# We'll use threshold=0.9 as an example
threshold=0.9 # High confidence
predicted_labels_list = []
for question in tqdm(df_original["Question"]):
    labels = predict_labels(question, threshold=threshold)[0]  # or pass a list in batches
    predicted_labels_list.append(labels)

df_original["final_QT"] = predicted_labels_list

# Instead of dropping rows with no confident label, we keep them.
# final_QT might be an empty list [] if nothing was above threshold.
df_original

# 1. Save the DataFrame to a CSV file
df_original.to_csv("c1_labeled_data.csv", index=False, encoding="utf-8-sig")

# 2. Download the file to your local machine (if you're in Colab)

import pandas as pd
df_original = pd.read_csv("c1_labeled_data.csv")
df_original

# Seeing how many labels that are empty
df_original["final_QT"].value_counts()

"""```
df_original = df_original[
    (df_original["final_QT"].str.len() > 0) &  # non-empty question labels
    (df_original["final_AT"].str.len() > 0)    # non-empty answer labels
]
```
"""
